user:
  name: 50
project:
  name: 100
time_sheet:
  employee_code: 7
  staff_name: 50
image_format_accept: "image/jpeg,image/gif,image/png"
image_width: 200
image_height: 200
per_page:
  admin:
    user: 10
  dashboard:
    project: 10
min_password: 6
workspace:
  per_page: 3
break_line: "<br>"
validation:
  workspace:
    name_max_len: 128
    des_max_len: 255
  section:
    name_max_len: 128
  location_type:
    name_max_len: 128
    color_max_len: 128
row_header: 5
data_row_first: 6
col_date_first: 3
row_title: 2
col_employee_code: 1
num_col_not_process: 6
format_date_to_timeline: "%H:%M:%S"
end_of_month: 31
end_day_pay: 25
month_year_of_timesheet: "%m/%Y"
file_xls: ".xls"
file_xlsx: ".xlsx"
slash: "/"
