user:
  name: 50
  user_request_leave:
    per_page: 10
project:
  name: 100
time_sheet:
  employee_code: 7
  staff_name: 50
image_format_accept: "image/jpeg,image/gif,image/png"
image_width: 200
image_height: 200
per_page:
  admin:
    user: 10
  dashboard:
    project: 10
    user: 10
    company_page: 10
    request_off: 5
    workspace: 10
  request_off: 5
min_password: 6
workspace:
  per_page: 3
break_line: "<br>"
validation:
  workspace:
    name_max_len: 128
    des_max_len: 255
  section:
    name_max_len: 128
  location_type:
    name_max_len: 128
    color_max_len: 128
row_header: 5
data_row_first: 6
row_excel_header: 1
row_excel_data_first: 2
col_date_first: 3
row_title: 2
col_employee_code: 1
num_col_not_process: 6
format_date_to_timeline: "%H:%M:%S"
end_of_month: 31
end_day_pay: 25
month_year_of_timesheet: "%m/%Y"
file_xls: ".xls"
file_xlsx: ".xlsx"
file_csv: ".csv"
slash: "/"
hour_minutes: "%H:%M"
employee_code_attribute: "employee_code"
name_attribute: "name"
